### ISSUE TITLE
Docker compose start fails

### ISSUE THREAD

**Issue by fpaparoni** [ISAITB/gitb#38]
I tried to start the project using the docker compose approach, simply downloading it from main branch (tested also 1.21.1 tag) and running the following command as stated in the README

` docker compose up -d --build`

but after some build processes I receive the following error

```
 => [gitb-ui internal] load build context                                                                                                  0.1s
 => => transferring context: 159.43kB                                                                                                      0.1s
 => ERROR [gitb-ui stage-1 2/4] RUN apk add --no-cache bash
```

What is wrong with my local setup? Using the dockerized build I suppose to launch everything only using the docker build.

**Comment by costas80** [comment]
Thanks for spotting this @fpaparoni . We've replicated the problem and are correcting it now.

I'll let you know as soon as the fix is in place.

**Comment by costas80** [comment]
@fpaparoni, the fix is now in place. Could you please confirm you have no more issues?

**Comment by fpaparoni** [comment]
Yes, the build now is working without problems, thank you
