### ISSUE TITLE
Error code while testing a service

### ISSUE THREAD

**Issue by Nicolas-Caroff** [ISAITB/gitb#51]
Hello,

I developped an API to expose lauch of extern test suites of a service from ITB. When I ran a test case on it, I got a 400 error code (bad request),  while the request works from the ITB docker container (by curl). I used _send_ and _receive_ steps to do it. By exchanging with Eliott Paillard, we found no obvious syntax problems in the tests. Does the translation of the request into ITB test cases require other steps, or is this an internal ITB problem ?

Thank you in advance

**Comment by costas80** [comment]
I'm not sure I understood correctly @Nicolas-Caroff. When you say you are using curl, you mean you are calling the Test Bed's [REST API](https://www.itb.ec.europa.eu/docs/itb-ta/latest/api/index.html#start) via curl to launch tests, or that you are trying to see if you can access the system that is being tested?

I believe your issue is that when executing the test case(s) you are getting 400-code errors reported by the system you are exchanging with. If this is the case it means that the system is receiving the calls but is rejecting them for some reason (to be checked in the other system's logs). I could maybe provide some extra insight if you share here the relevant log output from the `gitb-srv` container.

**Comment by Nicolas-Caroff** [comment]
I used curl to test the SUT from gitb-srv container. 
The SUT doesn't receive the request when I go through the ITB web interface and I get this in the gitb-srv logs : 
[logs.txt](https://github.com/ISAITB/gitb/files/15065085/logs.txt)

**Comment by costas80** [comment]
Thanks for the logs @Nicolas-Caroff. From the container logs I only see that the call is being received by the SUT but it is returning a status 400. Can you check the SUT's logs to see why it is rejecting he request?

**Comment by costas80** [comment]
There is one extra thing I noticed from the log. If you are calling a HTTPS endpoint note that the `HttpMessaging` handler only handles plain HTTP. You would have to use the `HttpsMessaging` handler for HTTPS.

This (and several other much more complex issues) is why the `HttpMessaging` handler is deprecated (same goes for the `HttpsMessaging one`). For simple cases of HTTP(s) calls we will be publishing shortly a new HTTP messaging handler that will address such issues and will be simpler to configure and use.

**Comment by Nicolas-Caroff** [comment]
Thanks for the quick answer. 
In the SUT logs, there's nothing when I execute the ITB test case. Since it's a Springboot app, I used the actuator to see the HTTP requests received. However, I didn't see any requests from ITB. 
The endpoints of my SUT are in HTTP and I use HttpMessaging for my test case.

**Comment by costas80** [comment]
That's odd as the 400 status is returned from the SUT... Would you mind sharing the test case you use? Maybe I could spot an issue with it.

**Comment by Nicolas-Caroff** [comment]
[Test_Suite.zip](https://github.com/ISAITB/gitb/files/15074514/Test_Suite.zip)

**Comment by Nicolas-Caroff** [comment]
yes, it's resolved

**Comment by costas80** [comment]
Hi @Nicolas-Caroff. If you want to try out the new messaging handler for making HTTP calls, we just published a preview of it on our development branch and nightly build channel. See [this comment](https://github.com/ISAITB/gitb/issues/50#issuecomment-2126791736) in issue #50 for details and examples (until the next release updates the published documentation).

Note that this currently supports only making HTTP calls to SUTs but we will be adding the possibility to have the Test Bed receive calls soon (I'll ping you again when this is published). If however you are currently only calling SUTs you can already switch to this.

**Comment by costas80** [comment]
Hi @Nicolas-Caroff. [Release 1.23.0](https://www.itb.ec.europa.eu/docs/itb-ta/latest/changeHistory/index.html) is now published, including the discussed bug fixes and the [new messaging handlers](https://www.itb.ec.europa.eu/docs/tdl/latest/handlers/index.html#built-in-messaging-handlers) we discussed.
