### ISSUE TITLE
Hosting the testbed on a subpath causes static assets to not render properly

### ISSUE THREAD

**Issue by KristofVDB1** [ISAITB/gitb#54]
Hi

We recently tried to deploy the testbed on a subpath of our domain. It works, but some of the static assets are being fetched from the root domain, and not the subpath, which means they are not available in the frontend. 
![Screenshot 2024-06-04 at 10 16 45](https://github.com/ISAITB/gitb/assets/28532087/7ea544da-4238-4bbe-9af2-bff214143a58)

I found this piece of documentation that talks about it https://www.itb.ec.europa.eu/docs/guides/latest/installingTheTestBedProduction/index.html#step-2-determine-the-access-url and tried to copy the setup as mentioned there. 

Our `docker-compose.yml` file: 

````docker
  gitb-ui:
    # The Test Bed's UI.
    image: isaitb/gitb-ui
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - AUTHENTICATION_COOKIE_PATH=/itb
      - TESTBED_HOME_LINK={ROOT}/itb

````

Our `NGINX` config file:

````nginx
location ~ /itb(/?.*) {
    add_header ITB-PATH /itb;

    proxy_pass   http://x.x.x.x:9000/$match$is_args$args;
}

````

I've obfuscated some parts for security reasons, but the general setup should be clear (at least I hope so). 

Am I missing something in this setup to allow the UI to be hosted succesfuly on a subpath, `/itb` in our case? Or did I misunderstood the documentation and is this something that's not supported out of the box.

Thanks as always

Kind regards
Kristof Vandenbroucke

**Comment by costas80** [comment]
Hi @KristofVDB1. Hosting under `/itb` should be fine. In fact it is exactly how we also host the Commission's own instance at https://www.itb.ec.europa.eu/itb/.

Checking your nginx configuration I see it doesn't match what is listed in the [installation guide](https://www.itb.ec.europa.eu/docs/guides/latest/installingTheTestBedProduction/index.html#step-7-configure-reverse-proxy):
```
http {
  ...
  # This is your HTTPS server.
  server {
    listen 443 ssl;
    ...
    location /itb/ {
      proxy_pass http://YOUR_INTERNAL_HOST:9000/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      add_header ITB-PATH /itb;
      add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains';
    }
    # The following location block is needed only if:
    # (a) You are receiving callbacks from test services, and
    # (b) These test services are remote and cannot use the test bed's local address.
    # location /itbsrv/ {
    #   proxy_pass http://10.0.0.4:8080/itbsrv/;
    # }
  }
}
```
There must be some issue with your `proxy_pass` directive of the `location` definition. Maybe try to define it as in the guide and go from there?

**Comment by KristofVDB1** [comment]
Hi @costas80 

Like always, thanks for the feedback. My initial NGINX config was a bit limited, but included more in the actual config. I started out from the actual NGINX config as provided by you guys and that seemed to go well.

````nginx
location ~ ^/itb/(.*)$ {
    add_header 'Access-Control-Allow-Origin' '*';
    add_header ITB-PATH /itb;
    add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains';
    
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

    proxy_pass http://x.x.x.x:9000/$1;
}
````

This is the config I'm currently using and it gives the following result: 
<img width="721" alt="Screenshot 2024-06-04 at 14 18 19" src="https://github.com/ISAITB/gitb/assets/28532087/e798821d-5ad6-49f9-8ea1-c6fd103a5f74">

And it results in the following:

````
Refused to apply style from 'https://{DOMAIN}/itb/assets/build/assets/build/styles.css?v=1.22.0_1' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
````

However, this is most likely something on our end that I'll have to fix. So as far as I'm concerned I think this issue can be closed. 

Kind regards
Kristof Vandenbroucke

**Comment by costas80** [comment]
No prob! By the way this kind of error ...
```
Refused to apply style from 'https://{DOMAIN}/itb/assets/build/assets/build/styles.css?v=1.22.0_1' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
... typically comes up when the CSS lookup results in an error (rendered as an HTML page). I would debug this by checking in your browser's developer tools the actual response for the CSS and going from there.

Regarding your current config it must be something related to the extension wildcard in your `location`. You should be able to define it without a modifier and regexp no?

**Comment by KristofVDB1** [comment]
Indeed, that seems to be the case. The location causes the URL to render the root of the application, rather than the static files. For example, `https://{DOMAIN}/itb/assets/build/assets/build/styles.css` this works, but with the `version` param, it does not work.

I might give you a heads up when I eventually fix it! 😉

**Comment by costas80** [comment]
> but with the version param, it does not work.

Keep in mind that query string parameters should be able to match against the `location` and go through though. Otherwise other things will similarly break down the line even if the static assets load.

Let me know if I can help at any point (we can keep this issue open until you resolve it).

**Comment by KristofVDB1** [comment]
Just for the sake of being complete, I'll close this issue. Thanks again for all the help!
