### ISSUE TITLE
PATCH request with HttpMessagingv2

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#55]
Hello @costas80,
It looks like PATCH method is not usable with the new handler.
<img width="358" alt="image" src="https://github.com/ISAITB/gitb/assets/143092948/77a90a8a-d0a9-44b7-a6f4-e64a4e9c16ae">
[example.zip](https://github.com/user-attachments/files/15718515/example.zip)

**Comment by costas80** [comment]
Hi @EliottPaillard. Thanks for spotting this! An update was just pushed to the nightly build channel that adds support for PATCH (and also HEAD, TRACE and OPTIONS that were missing from the initial implementation).

By the way, you will be pleased to know that the handler now also supports receiving requests albeit with a completely different approach to the previous HttpMessaging handler's implementation. In brief you can use something like this ...
```xml
<receive desc="Receive POST" from="Actor1" to="Actor2" handler="HttpMessagingV2">
   <input name="method">"POST"</input>
   <input name="body">"ALL OK!"</input>
</receive>
```
... to receive to a POST and respond with a "200" (the default) and an "ALL OK!" body. In this case the POST will be expected to be made to (assuming a developer Test Bed instance with the gitb-srv container exposed to port 8080) `http://localhost:8080/itbsrv/api/http/API_KEY`, where `API_KEY` is the system's API key that is listed in the system details' screen:

![image](https://github.com/ISAITB/gitb/assets/8297297/56e55797-1dfc-48c0-82b3-909314a2c7c7)

Note that when a receive step is executed you also get a log entry added to the test session log:

![image](https://github.com/ISAITB/gitb/assets/8297297/e326f4bc-0f16-49b8-8532-c78963c181d3)

As you may have noticed the system API key would be the same for all test sessions, meaning that if you have multiple parallel test sessions for the same system, the Test Bed will be matching incoming calls to all pending receive steps (which is likely not what you want). To address this you can either force sequential execution of the test case in question by setting the [supportsParallelExecution](https://www.itb.ec.europa.eu/docs/tdl/latest/testcase/index.html) attribute ...
```xml
<testcase ... supportsParallelExecution="false">
   ...
</testcase>
```
... or by using a specific `uriExtension` in the receive step (which can also be used to simply add an extra fixed path to the URI). For example you can use this to add a fixed path plus a variable value (depending on your specs and testing logic of course):
```xml
<receive desc="Receive POST" from="Actor1" to="Actor2" handler="HttpMessagingV2">
   <input name="uriExtension">"/extra/" || $variable || "/path"</input>
   <input name="method">"POST"</input>
   <input name="body">"ALL OK!"</input>
</receive>
```
Full docs on the new receive possibilities for the HttpMessagingV2 handler will be published in the TDL docs in the next release. If you want to use it before the release is published and are wondering about other options feel free to ping me (just make an extra issue).

**Comment by EliottPaillard** [comment]
That's sounds great ! 
Regarding the PATCH method, it's working well now, thank you for your reactivity as always !
