### ISSUE TITLE
[Question] HttpMessagingv2 only triggered if not empty

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#57]
Hello @costas80

I want to use a scriptlet calling a "send" from the httpMessagingV2 handler.
Sometimes it would use a queryParameters input but sometimes not.

Should I make two different scriptlets, one asking for this input and the other not,
or is there a clean way to make the operation only use the queryParameters if it's not empty ?

Tell me if It's understandable for you.
Thank you !

**Comment by costas80** [comment]
Hi @EliottPaillard

In your `send` step you could always pass in the `queryParameters` whether they are empty or not. If empty, the result will be the same as if you hadn't passed any input. More of an issue is the input parameter for the scriptlet, as the only way to have optional parameters is to provide a default value for them.

Considering this I'm sharing below the best I could come up with to have a single scriptlet and without adding anything outside the scriptlet itself.

The scriptlet would be something like the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<scriptlet id="callService" xmlns="http://www.gitb.com/tdl/v1/">
    <params>
        <!-- Set a default value to the map with a special value to check here. -->
        <var name="params" type="map"><value name="NONE" type="string">true</value></var>
    </params>
    <steps>
        <!-- Hidden step to clean the params map if it has not been provided as an input. -->
        <if hidden="true">
            <cond>$params{NONE} = "true"</cond>
            <then>
                <process output="params" handler="CollectionUtils" operation="clear" input="$params"/>
            </then>
        </if>
        <send desc="Send message to system" from="Actor1" to="Actor2" handler="HttpMessagingV2">
            <input name="uri">"http://localhost:9999/app/get"</input>
            <input name="method">"GET"</input>
            <input name="queryParameters">$params</input>
        </send>
    </steps>
</scriptlet>
```
With this placed under say `scriptlets/callService.xml` you could use it as follows from a test case:
```xml
<steps stopOnError="true">
    ...
    <!-- Call scriptlet without query parameters. -->
    <call path="scriptlets/callService.xml"/>

    <!-- Call scriptlet with query parameters. -->
    <assign to="queryParams{key}">"value"</assign>
    <call path="scriptlets/callService.xml">
        <input name="params">$queryParams</input>
    </call>
    ...
</steps>

```

This would be simpler if we could initialise a map (or list for that matter) scriptlet parameter as empty but this is not possible currently (I'll add it to the backlog for a future release however).

What do you think?

**Comment by costas80** [comment]
Hi @EliottPaillard. You likely got the release notification that [v1.23.0](https://www.itb.ec.europa.eu/docs/itb-ta/latest/changeHistory/index.html) is now published. This includes all fixes we have been discussing in the previous weeks as well as the new `HttpMessagingV2` handler. This is now also documented in the [TDL documentation](https://www.itb.ec.europa.eu/docs/tdl/latest/handlers/index.html#httpmessagingv2), and also figures in the updated [guide on simple test case messaging](https://www.itb.ec.europa.eu/docs/guides/latest/sendingAndReceivingContent/index.html).

**Comment by EliottPaillard** [comment]
I feel that for now, regarding the structure of my tests and my scriptlets I will keep multiple scriptlet, It feels more appropriate.
However, I have no doubt this could be useful for me in the future, thank you for the example!

Nice! Again, thank you for your work and your reactivity, it's really great to know you watch my back. I will let you know if I find anything relevant to feedback about the documentation
