### ISSUE TITLE
[Question] Using a custom report template

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#58]
Hello @costas80,

We're thinking about maybe use our own custom test session report template.
We have already some tools from our side to convert an xml file in a PDF one and I was wondering if it would be possible to use them to allow users to download our report directly from ITB.

I believe ITB does not propose to use a custom converter yet. Do you think it is possible for ITB to offer this kind of things?

**Comment by costas80** [comment]
Hi @EliottPaillard.

That sounds like a nice feature. Currently if you connect as a community (or Test Bed) admin you can [configure report settings](https://www.itb.ec.europa.eu/docs/itb-ta/latest/communityDashboard/index.html#edit-report-settings) for a community. There are options here for customising the built-in PDF reports for a conformance statement/overview certificate but for other kinds of reports (conformance statement/overview report, test case report, test step report) we only provide the possibility to configure an XSLT to customise the report when produced in XML.

Based on what you suggest I would foresee the possibility to configure a REST service to which the XML report will be posted and that will expect a response with the PDF report to download for the user. Like that you will be able to use your converter implementation directly assuming you wrap it with a simple API.

If this sounds good (please confirm) I'll add it to the backlog for implementation.

**Comment by costas80** [comment]
Hi @EliottPaillard. The feature you requested is now available on our nightly channel. If you go to the **Report settings** under the community's management you have the option for any type of report to delegate its generation to a custom service. For example for a test case report you have the following:

![image](https://github.com/user-attachments/assets/d10f4d21-51cb-4215-872d-5c3df4cabd89)

When generating the report, the configured service will receive a HTTP POST with the report in XML format as its payload. The expected response will be the generated PDF that will then be provided to the user. Note that previously for the XML report you could also configure a custom XSLT stylesheet to adapt it if needed. In this case, when delegating PDF report generation to your own service, you can also choose whether you want to apply the stylesheet to the XML report before calling. Finally, you can also choose to sign the PDF report if you have a signing certificate configured.

I trust this covers you but as always I'd be happy to get any feedback/comments.

By the way, if testing this locally do keep in mind that you are running the ITB via Docker. On a Windows workstation this means that you wouldn't point to a localhost service as e.g. `http://localhost:8484/service` but rather `http://host.docker.internal:8484/service` (I get this question a lot :))

**Comment by EliottPaillard** [comment]
Hey @costas80, thanks a lot for the update (and for the gentle reminder as well :))

We will try to use this new feature soon, I'll keep you informed

**Comment by costas80** [comment]
This feature was released as part of release 1.24.0.
