### ISSUE TITLE
Error message implementing validation service

### ISSUE THREAD

**Issue by Nicolas-Caroff** [ISAITB/gitb#59]
Hello, 

I try to develop a custom validation service. So I followed this documentation : https://www.itb.ec.europa.eu/docs/services/latest/validation/index.html
but when I used it in an ITB test case, I got this error.
<img width="370" alt="image" src="https://github.com/ISAITB/gitb/assets/167754582/11a7c256-f67a-43d3-bb77-96d2b6dfd7ed">
Do you have any idea what went wrong?

**Comment by costas80** [comment]
Hi @Nicolas-Caroff. Such an error would come up if the backend test engine component (that would be **gitb-srv**) can't access the WSDL of your validation service.

The best way to debug this would be to get shell access on the **gitb-srv** container and try to access that exact URL using something like curl or wget. If that works then you'll also be able to use the service in your test case.

Also, if the validation service is also exposed on your localhost (I'm assuming you're running everything on your workstation while developing), try to access via your browser on your localhost.

**Comment by Nicolas-Caroff** [comment]
When I am using curl to access the URL, I get a 404 Not Found error.

**Comment by Nicolas-Caroff** [comment]
When I am using curl to access the URL, I get a 404 Not Found error.

**Comment by costateixeira** [comment]
i am getting the same.  This is working in the could instance without using the processing service, but now I redeploy locally and I see this issue and I don't know what I am missing.

sorry for n00b and potentially unrelated question, but the BeanConfig.java does have this
    @Bean
    public EndpointImpl processingService(Bus cxfBus, ProcessingServiceImpl serviceImplementation) {
        EndpointImpl endpoint = new EndpointImpl(cxfBus, serviceImplementation);
        endpoint.setServiceName(new QName("http://www.gitb.com/ps/v1/", "ProcessingServiceService"));
        endpoint.setEndpointName(new QName("http://www.gitb.com/ps/v1/", "ProcessingServicePort"));
        endpoint.publish("/process");
        return endpoint;
    }

when I open http://localhost:9002/fhir/services, i only see ValidationService and MessagingService. should processingService be there?

if off-topic and unrelated to this issue, would you please let me know? I'll remove or hide this comment in that case. I am posting in case it is usefule and related

**Comment by costas80** [comment]
> When I am using curl to access the URL, I get a 404 Not Found error. 

Ok so there's an issue with the validator app or the provided address is wrong. Have you checked in its own container logs if this has started as expected?

Also the hostname you are using suggests you are running this in the same Dockerised service as the Test Bed's components and that the hostname matches the name of the service (as defined in your docker-compose). Can you check/confirm this?

**Comment by costas80** [comment]
@costateixeira, the container of your supporting services app should be listing in its logs the SOAP endpoints that are being created, including the missing processing service. I wonder from your description whether this is a mixup of running apps where you have multiple instances running locally for your supporting services app (e.g. one within your Dockerised and another instance created separately).

Also if the processing service is part of new development are you sure this has been built from source, the container image is rebuilt, and the running container has been replaced considering the new image? (sorry for stating the obvious but best to run through all possibilities)

**Comment by Nicolas-Caroff** [comment]
Container logs from ITB say more or less the same thing and those from my validation service are normal. It starts correctly. I feel the issue is in my validation service because I don't see any other possible URL.
ITB's container and validation service's container are in the same docker network.

**Comment by Nicolas-Caroff** [comment]
Container logs from ITB say more or less the same thing and those from my validation service are normal. It starts correctly. I feel the issue is in my validation service because I don't see any other possible URL.
ITB's container and validation service's container are in the same docker network.

**Comment by costas80** [comment]
Thanks for checking @Nicolas-Caroff. The most likely issue then is the address you use for the WSDL. Some obvious things I can see are (assuming you are building the validation service as a Spring Boot app as per the docs):
- Possibly a missing application context path. If you have one set this would be present in `application.properties` as property `server.servlet.context-path`.
- The root path for the CXF servlet that publishes the app's SOAP services. By default this is `/services`. 

In the most likely case that you don't have an application context set and use the default CXF mapping, this means that the WSDL address would be:

`http://soap-ogc:8080/services/validation?wsdl`

Can you try this out?

**Comment by Nicolas-Caroff** [comment]
Indeed with this address, I get WSDL document. Is it normal that it didn't lauch validation process ?

**Comment by Nicolas-Caroff** [comment]
Oh I get this error on ITB
<img width="344" alt="image" src="https://github.com/ISAITB/gitb/assets/167754582/6295496d-59ff-4d72-b583-ee9751732002">
I thought I'd made it optional. When you declare a typed parameter, the value Usage Enumeration.O for the Use attribute doesn't mean that ?

**Comment by Nicolas-Caroff** [comment]
Do you mean create create my own methods to parse parameters or a existing specific class ? I saw an Utils class with various methods with different purposes.

**Comment by costas80** [comment]
Indeed there is a Utils class there that I imagine you are using to get your input parameters. It's probably one of those methods that you are using and that is throwing the "single required input" error you see.

Also, it's not "parsing" really. You get a map with key-value pairs for inputs. You can easily just use that directly to get the input you want. But do check the Utils class in any case. I believe there are already helper methods to get optional values. If missing though, of course you can create any other methods that do what you want.

**Comment by costas80** [comment]
Hi @Nicolas-Caroff, just a quick note that based on your feedback the [services' docs](https://www.itb.ec.europa.eu/docs/services/latest/validation/index.html#configuring-the-web-service-endpoint) were improved to clearly highlight the default WSDL URL someone should expect when creating a new service:

![image](https://github.com/ISAITB/gitb/assets/8297297/24e6d7e1-7396-4c46-b052-f1cdaac0fae6)

Hopefully this helps others avoid similar issues in the future.

By the way, I assume this issue is resolved for you right? If yes we can close the issue.
