### ISSUE TITLE
ITB and Webhooks

### ISSUE THREAD

**Issue by Nicolas-Caroff** [ISAITB/gitb#62]
Hello,

I heard about the existance of webhooks in ITB but I am not able to find any documentation. Are webhooks still relevant today, and is there any documentation on them? If so, I would like to have it if possible.

**Comment by costas80** [comment]
Hi @Nicolas-Caroff. Indeed the ITB does have webhooks (they are called "triggers"). There's a full section in the user guide on those: https://www.itb.ec.europa.eu/docs/itb-ta/latest/communityDashboard/index.html#manage-triggers

**Comment by Nicolas-Caroff** [comment]
From what I see, we can create and manipulate these triggers from the web interface. But can we do the same through a REST API ?

**Comment by costas80** [comment]
I assume you mean creating such triggers from the REST API? If yes then indeed it's not possible. Of course, once created from the UI, configured triggers will execute regardless of how the relevant events took place (e.g. via a test session completed through the UI or via REST API).

In case you are looking more towards preconfiguring a set of triggers automatically, you can do this if you are creating the target Test Bed instance as what we call a [sandbox instance](https://www.itb.ec.europa.eu/docs/guides/latest/definingASandbox/index.html). In brief:

1. In a development instance you create all the data you need (community, domain, organisations, user accounts, specifications, ..., and also triggers).
2. You export the configured community as an archive.
3. For the target instance you provide the archive at a special "input" folder (see the guide for details) from which the data will be read (only once) at start-up. Doing so the new Test Bed instance will be created from scratch with preconfigured data including the triggers you have defined.

You typically define such sandbox instances if you want to provide downstream users a preconfigured testing package, or if you want to spin up a Test Bed instance with predefined configuration for use in CI/CD processes.

Would this approach be helpful?

**Comment by Nicolas-Caroff** [comment]
I'm currently starting a project linked to ITB. So I'm trying to get a clearer idea of the different approaches. This could be one of them.

**Comment by costas80** [comment]
Great! The ITB has multiple features and different ways of being used (centralised/decentralised, UI/REST API, sandbox instances, ...). We could have a call (a Teams meeting) in which we can discuss what you need and go over the different approaches together. If you'd like this just us an email at DIGIT-ITB@ec.europa.eu and we can plan it.

**Comment by costas80** [comment]
I don't believe there was anything left to cover here so I'm closing the issue.
