### ISSUE TITLE
Validation service timeout error

### ISSUE THREAD

**Issue by Nicolas-Caroff** [ISAITB/gitb#63]
Hello,

I'm still implementing a validation service. The validation is quite long and so _verify_ step return this error : 
<img width="350" alt="image" src="https://github.com/ISAITB/gitb/assets/167754582/9b106a88-ec3a-48b1-902b-a7db576736df">
Would it be possible to increase the timeout to make it work ?

**Comment by costas80** [comment]
Hi @Nicolas-Caroff. I'll try to replicate this and see what we could do. Increasing a timeout at this level is not possible currently but we can no doubt foresee some configuration to make it possible.

Out of interest and to help with replicating this, how long does the validation need more/less?

**Comment by Nicolas-Caroff** [comment]
This can vary from a few seconds to around ten minutes, depending on the number of tests carried out. In general, it's a couple of minutes.

**Comment by costas80** [comment]
Ok thanks. Implementation-wise we need to approach this differently based on what you say. Currently calls to supporting services are synchronous but if calls can last minutes this will hog threads even if the timeout is increased. I'll look into this and get back to you, but in any case switching to full-asynchronous with permissive timeouts shouldn't be too difficult.

**Comment by costas80** [comment]
Hi @Nicolas-Caroff, the update is now available if you pull the latest [nightly build](https://www.itb.ec.europa.eu/docs/guides/latest/onboardingDevelopers/index.html#using-nightly-builds). With this update the response timeout from the service is altogether removed, leaving only a connection timeout to establish the initial connection.

We preferred to remove the response timeout given that such test extension services (like the validation service you referred to) are a key part of the test setup, and it makes sense to give them as much time as needed. To better support this, external calls are now handled via a dedicated thread pool to avoid several long-lasting validations from parallel test sessions hogging core threads.

Would you confirm if this works for you once you've had a chance to try it out?

**Comment by Nicolas-Caroff** [comment]
Yes, it works now. Thanks.

**Comment by costas80** [comment]
Great! Besides the nightly channel, this will figure in the next stable release. Make sure you subscribe to release notifications to get notified.
