### ISSUE TITLE
Timeout element

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#70]
Hello @costas80,

Before we could set a timeout as an element of the receive tag.
But as we only use the send tag now, and as it doesn't support a timeout element yet,
I think we can't set a timeout anymore when calling the SUT and waiting for a response.

**Comment by costas80** [comment]
Hi @EliottPaillard. Indeed the `send` is a synchronous step and underlying call. The purpose of the timeout on the `receive` step is to limit how much time the Test Bed will wait for a call from the SUT.

It seems you are referring to setting something like a connection timeout or a read timeout when the Test Bed is calling the SUT via the `send` step. Is this what you're going for? Do you see any use case where a connection timeout would e.g. be considered as a success?

**Comment by EliottPaillard** [comment]
Yes I would like to set a connection timeout but to be considered as a failure.
Here I'm trying to test the response of a call to the given endpoint.
And failures would be, ITB can't connect to the SUT or a connection timeout appears

**Comment by costas80** [comment]
I see. We could easily support a configurable connection timeout as an input parameter of the `HttpMessagingV2` handler. We'll work on that asap and I'll let you know when ready.

**Comment by EliottPaillard** [comment]
Great to know, thank you

**Comment by costas80** [comment]
Hi @EliottPaillard. The nightly image is now updated with two new timeout inputs for `HttpMessagingV2` as follows:
* `connectionTimeout`: The milliseconds to wait for until a connection is established with the target (default is 10000 - 10 seconds).
* `requestTimeout`: The milliseconds to wait for until the full request completes (no default meaning wait indefinitely).

For your use case I believe the `requestTimeout` is most interesting. If for example you want to call the SUT and ensure that it responds within 30 seconds you would set it as follows:
```
<send desc="Send message" from="Actor1" to="Actor2" handler="HttpMessagingV2">
   ...
   <input name="requestTimeout">30000</input>
</send>
```

The `connectionTimeout` can of course be used but depends on the target server implementation. For example if the server responds that the connection is refused or closed this timeout will not apply. For it to apply you would need to have a delay in looking up the target host, or in the host taking some time to accept the incoming socket.

Finally note that in both cases setting a zero or negative value is the same as applying the default. This could be useful for example if you set/disable the timeouts configurably, in which case you could switch a config property between a valid value (e.g. 30000) and -1 (to disable it).
```
<send desc="Send message" from="Actor1" to="Actor2" handler="HttpMessagingV2">
   ...
   <!-- Set the requestTimeout domain parameter to -1 or e.g. 30000 -->
   <input name="requestTimeout">$DOMAIN{requestTimeout}</input>
</send>
```

**Comment by EliottPaillard** [comment]
That's good for me!
Thank you @costas80
