### ISSUE TITLE
Type 'File'

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#78]
Hello @costas80,

Tell me if I'm wrong but I think there is no type 'File' existing in ITB?

I'm looking for the most simple way to retrieve both the name of a file and its content when using the interact input provided by a user.

**Comment by costas80** [comment]
Hi @EliottPaillard,

For uploading files via the `interact` step the simplest way is to set the `inputType` to `UPLOAD`:

```xml
<interact id="data" desc="Get data">
    <request name="file" desc="Upload your file:" inputType="UPLOAD"/>
</interact>
<!-- The file is available at $data{file} -->
```
From what you are saying I assume you are aware of this but also want to record the name of the uploaded file (besides its content) right? If so this isn't possible currently but we could easily support it with a new attribute to record the file name. For example if this is called `fileName` the step above would look something like this:
```xml
<interact id="data" desc="Get data">
    <request name="file" fileName="name" desc="Upload your file:" inputType="UPLOAD"/>
</interact>
<!-- The content of the file is available at $data{file} and the name at $data{name} -->
```

I assume this would cover your needs?

**Comment by EliottPaillard** [comment]
Hey @costas80,
yes, you understood perfectly.

**Comment by EliottPaillard** [comment]
We will be find, thank you Costas

**Comment by costas80** [comment]
Hi @EliottPaillard. This is now available in the latest nightly build.

In terms of usage, this follows what we had discussed previously: You can specify a **fileName** attribute for each file input, setting it to the value of the key in the interact step's map that will hold the file name. Moreover, you can also define this dynamically by setting **fileName** as a variable reference. The following example illustrates both cases:

```xml
<assign to="fileNameVariableName">"imageFile2"</assign>
<interact id="data" desc="Provide inputs">
   <request desc="Provide image 1" name="image1" fileName="imageFile1" inputType="UPLOAD"/>
   <!-- Setting the key dynamically (if needed) -->
   <request desc="Provide image 2" name="image2" fileName="$fileNameVariableName" inputType="UPLOAD"/>
</interact>
<!-- The file's content is available at $data{image1} whereas the name of the file is available at $data{imageFile1} -->
<log>$data{imageFile1}</log>
<!-- Similarly for the second file, the file is available at $data{image2} and the name at $data{imageFile2} -->
<log>$data{imageFile2}</log>
```

I trust this convers your case?

**Comment by costas80** [comment]
Pinging you @EliottPaillard to see if we can close this (see previous comment).

**Comment by EliottPaillard** [comment]
Indeed, my case is covered, thank you!
