### ISSUE TITLE
Unexpected Error while creating conformance statements

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#82]
Hey @costas80,

I never encountered this before few days ago.
But now, and with the same configuration as I have for months, an error appears while creating conformance statements.
<img width="377" alt="image" src="https://github.com/user-attachments/assets/669baba2-1d40-4d5e-a3ac-4c80dc16c3ab">

**Comment by costas80** [comment]
Hi @EliottPaillard. That rings a bell. It was a regression that made itself into the nightly build a few weeks ago but was since fixed. You probably had pulled an affected build before it was corrected.

Can you pull the latest nightly build and try?

**Comment by EliottPaillard** [comment]
It looks good so far, thank you
