### ISSUE TITLE
"-" in ITB account passwords

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#83]
Hey @costas80,

We somehow find out that "-" doesn't count as a special character in ITB account passwords.
Is it an intended behaviour?

**Comment by costas80** [comment]
Yup, that's an omission. The problem seems to be with the regexp we use to check the passwords' complexity.

We'll fix that asap (I'll let you know when you can pull the fix).

**Comment by costas80** [comment]
Ready to go @EliottPaillard! The latest nightly build includes the fix.

By the way we'll be release this week the next stable release (1.24.0). Make sure you are subscribed to release updates to get the ping!

**Comment by costas80** [comment]
This issue was corrected with release 1.24.0.
