### ISSUE TITLE
Specify trigger for a test suite

### ISSUE THREAD

**Issue by Nicolas-Caroff** [ISAITB/gitb#84]
Hello @costas80

We have developed a gateway between an intern tool and ITB. This system is used by DIGIT to execute different test suites. But they want to use it, only on some of them inside a community and our system is using community triggers to get the report. Because it is at community level we can't manage to do that. So we would like to know if it is possible to add filters in the trigger's configuration to select test suites we want to set the trigger on.

**Comment by costas80** [comment]
Hi @Nicolas-Caroff. What type of trigger have you defined for this? A trigger on test session completion for example?

**Comment by costas80** [comment]
So, I'm not sure I fully understood your setup but from what I understand the most important point is this:

> add filters in the trigger's configuration to select test suites we want to set the trigger on.

However if you are using test session succeeded and failed triggers, you get as part of the payload the **testSuiteIdentifier** and the **testCaseIdentifier**. Based on these you can figure out whether you want to take action or not, no?

Generally when you have a system that exposes a webhook feature (like the triggers in the ITB), you don't see too many fine-grained customisation options on the kind of filtering you suggest. Moreover filtering logic could vary greatly between different users/projects so trying to cover all cases would be overly complex. The normal approach is that the webhook/trigger payload exposes to you all the metadata you would need to decide if you take action and what to do. Why can't you decide this on the receiving end?

**Comment by costas80** [comment]
As an extra thought here, we could potentially foresee a new event type for triggers to capture the start and end of a complete test suite's execution, but still I don't think this would help you (given your concern is more on the filtering of fired triggers).

**Comment by Nicolas-Caroff** [comment]
Our system, when it receives data that does not concern it, it ignores them. But DIGIT wants to avoid sending data to our tool when it should not.

**Comment by costas80** [comment]
Ok that makes sense.

Given what you described and what we currently support I would design this in a more generic way. I would foresee a **trigger filter** configuration that would allow you to specify either when the trigger should fire or should not fire. This feature could cover eventually additional event types but to begin with we can start with:
* Test session started
* Test session succeeded
* Test session failed

In these cases you will be able to use certain data to define such a filter, specifically:
* Test suite identifier
* Test case identifier

To avoid making this configuration too fine grained and difficult to maintain (e.g. having multiple test suites with the same identifier, adding or removing test suites, communities with multiple domains, ...) I would simplify this by allowing the community administrator to define single filter expressions using **regular expressions**. Like this for example you could specify that the trigger would fire for all test suites ending with "_V1". You can also be as specific as you like with regular expressions, tuning them for specific or multiple matches depending on what you need.

In addition, I would also see filters as complementary (applied with "and" logic). You could for example define for a single trigger on test session completion three filters as such:
* Apply for all test suites ending with "_V1".
* Skip test suites starting with "internal_".
* Skip test cases ending with "_optional".

This would mean that a test session completing would fire that trigger only if all the configured filters match.

This should cover your needs no?

**Comment by costas80** [comment]
Ok thanks @Nicolas-Caroff - we'll add this to our backlog and work on it asap. I'll let you know here when the feature becomes available to use on our nightly channel.

**Comment by costas80** [comment]
Good news @Nicolas-Caroff - the discussed feature is now available on our nightly build channel.

In brief, when defining a trigger for events related to test sessions (started, succeeded or failed) you can now define an optional "**Fire condition**" that needs to be satisfied for the trigger to fire. The condition can include multiple clauses based on the test suite and test case identifiers, a regular expression to apply on the value, and a flag on whether or not you want to inverse the check (i.e. pass if the expression does not match).

You can define multiple clauses in a condition that all need to be satisfied (applying "AND" logic). However, given the expressiveness of regular expressions you can also apply "OR" logic within each clause. Finally, note that regular expressions are satisfied with partial matches (although you can still use start/end anchors), meaning that you can mix and match several to apply complex logic if needed.

As an example, consider the following condition:

![image](https://github.com/user-attachments/assets/2f2888c0-9b0c-45bf-9f94-de73f5574590)

The defined clauses mean that the trigger will fire only if:
* The test suite identifier starts with either `test_suite_1_` or `test_suite_2_`.
* The test case identifier does not end with `_optional`.
* The test case identifier includes a text such as `_UC.15_`.

To make sure you are defining correct expressions, you can also test via the UI individual clauses ...

![image](https://github.com/user-attachments/assets/def6358a-1ba8-4fdc-925c-01f4e61e6259)

... but also the complete condition:

![image](https://github.com/user-attachments/assets/1d31537a-a954-4a7d-b64e-b9f1ac3621d7)

I trust that with these conditions your use case is fully covered (let me know here if you think something else is needed). Finally, note that we could extend such conditions to also apply to other values (e.g. specific organisations/systems/specifications) but I wanted to start from your current need as the first step.

**Comment by costas80** [comment]
As an update to my previous comment, the available options to manage the triggers' firing is now extended (we went ahead with this already as it was quite easy following the first implementation). This means that you can define fire conditions for **any type of trigger**, and base their conditions on **any of their applicable data**.

In the case of triggers linked to test sessions, you can define conditions based on:
* The test case, test suite and test session identifiers (as was mentioned previously).
* The relevant actor, specification, system and organisation.

For example using these new options you could now also specify that triggers should only fire for certain specifications, and even for certain organisations.

**Comment by Nicolas-Caroff** [comment]
Super, I did some tests on our instance and it seems to work as we want.

**Comment by costas80** [comment]
Thanks for the feedback @Nicolas-Caroff. I'll proceed to close the issue but feel free to reopen if anything comes up.
